# Generated by Django 5.0.7 on 2024-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                (
                    "account",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="계정(아이디)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="비밀번호")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="회원 활성화 여부"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="관리자 여부"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="슈퍼유저 여부"),
                ),
                (
                    "is_lunch_rec_allowed",
                    models.BooleanField(
                        default=False, verbose_name="점심 추천 허용 여부"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(default=37.54985506398236, verbose_name="위도"),
                ),
                (
                    "longitude",
                    models.FloatField(default=126.99731087531654, verbose_name="경도"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
    ]
