# Generated by Django 5.0.7 on 2024-08-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="시 명칭")),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="위도"
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="경도"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
