# Generated by Django 5.0.7 on 2024-08-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={"verbose_name": "Province", "verbose_name_plural": "Provinces"},
        ),
        migrations.AlterModelTable(
            name="province",
            table="province",
        ),
    ]
