# Generated by Django 5.0.7 on 2024-08-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("province", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RdRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                ("sigun_nm", models.CharField(max_length=255)),
                ("sigun_cd", models.CharField(blank=True, max_length=255, null=True)),
                ("bizplc_nm", models.CharField(max_length=255)),
                ("licensg_de", models.CharField(max_length=100)),
                ("bsn_state_nm", models.CharField(max_length=50)),
                ("clsbiz_de", models.CharField(blank=True, max_length=100, null=True)),
                ("locplc_ar", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grad_faclt_div_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "male_enflpsn_cnt",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("yy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "multi_use_bizestbl_yn",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "grad_div_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tot_faclt_scale", models.IntegerField(blank=True, null=True)),
                (
                    "female_enflpsn_cnt",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "bsnsite_circumfr_div_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sanittn_indutype_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sanittn_bizcond_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tot_emply_cnt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "refine_lotno_addr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "refine_roadnm_addr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "refine_zip_cd",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "refine_wgs84_logt",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=15, null=True
                    ),
                ),
                (
                    "refine_wgs84_lat",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "RdRestaurant",
                "verbose_name_plural": "RdRestaurant",
                "db_table": "raw_data_restaurant",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Genrestrtfastfood", "중국식"),
                            ("Genrestrtjpnfood", "일식"),
                            ("Genrestrtsoup", "탕류(보신용)"),
                            ("Genrestrtstandpub", "정종/대포집/소주방"),
                            ("Genrestrtchifood", "패스트푸드"),
                        ],
                        max_length=50,
                        verbose_name="음식점 분류(위생업태명)",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="사업장명")),
                (
                    "status",
                    models.CharField(
                        choices=[("영업", "영업"), ("폐업", "폐업")],
                        max_length=2,
                        verbose_name="영업상태명",
                    ),
                ),
                (
                    "road_addr",
                    models.CharField(max_length=255, verbose_name="소재지도로명주소"),
                ),
                (
                    "lot_addr",
                    models.CharField(max_length=255, verbose_name="소재지지번주소"),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="위도"
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="경도"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, default=0.0, max_digits=3, verbose_name="평점"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="province.province",
                        verbose_name="시군구",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "restaurant",
                "unique_together": {("name", "lot_addr")},
            },
        ),
    ]
