# Generated by Django 5.0.7 on 2024-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.CharField(
                choices=[
                    ("중국식", "중국식"),
                    ("일식", "일식"),
                    ("탕류(보신용)", "탕류(보신용)"),
                    ("정종/대포집/소주방", "정종/대포집/소주방"),
                    ("패스트푸드", "패스트푸드"),
                ],
                max_length=50,
                verbose_name="음식점 분류(위생업태명)",
            ),
        ),
    ]
